services:
  # 1. La Base de Datos
  db:
    image: postgres:15-alpine
    container_name: mi_casino_db_container
    restart: always
    environment:
      - POSTGRES_USER=admin_casino
      - POSTGRES_PASSWORD=casino_pass_2026
      - POSTGRES_DB=mi_casino_db
    ports:
      - "5432:5432"
    volumes:
      - mi_casino_data:/var/lib/postgresql/data

  # 2. Administrador de DB (pgAdmin)
  mi_casino_admin:
    image: dpage/pgadmin4
    container_name: mi_casino_pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@casino.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    depends_on:
      - db

  # 3. El Cerebro IA (Python + Flask)
  mi_casino_flask:
    build: ./python_model
    container_name: mi_casino_flask_container
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://admin_casino:casino_pass_2026@db:5432/mi_casino_db
    volumes:
      - ./python_ia:/app
    depends_on:
      - db

volumes:
  mi_casino_data: